name: DocsQA Trigger

on: workflow_dispatch

jobs:
  trigger-docsqa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: deepankarm/sample-action@main
        with:
          repo: chunyuema/pydantic
          token: ${{ secrets.ACCESS_TOKEN }}
